[package]
name = "advent_of_code"
version = "0.0.1"
authors = ["Marc Jovani"]
edition = "2023"
default-run = "advent_of_code"

[lib]
doctest = false

[features]
test_lib = []

[dependencies]
pico-args = "0.5.0"
